### PR TITLE
NEUBURG-58: really delete offers

### PR DESCRIPTION
**Pull request by NKlug**

### CODE REVIEW

**Comment by michael-markl** [comment]
Do we need to remove the `deleted` flag from the model?

**Comment by NKlug** [comment]
We don't have to but we can as far as I can see. I left it in since I was not 100% sure we will not need it again.

**Comment by michael-markl** [comment]
I think we should get rid of it - otherwise our data structure gets too complicated: sometimes we really delete, sometimes we only set the flag... We would also always have to check for the flag to be false in most cases (error prone) :thinking:

**Comment by NKlug** [comment]
Alright, then I'll delete it.

**Review by michael-markl — APPROVED** [review]

**Pull request merged**
